### ISSUE TITLE
Wheels

### ISSUE THREAD

**Issue by burf2000** [grassjelly/linorobot#1]
Hi there, do you still do ROS?  I am building a similar robot and I am stuck on 1 thing which I would absolutely love help with.

I am using Hector Slam which produces /odom etc for my lidar.  I have a URDF.  How do I link the wheel in the mode (mine is lwheel, yours is wheel_left) to the system as it always shows as an error in RVIZ?

**Comment by grassjelly** [comment]
hi @burf2000 You can start a thread here https://groups.google.com/forum/#!forum/linorobot so the rest can see your question as well.

**Comment by burf2000** [comment]
Done, if someone can help me, I can pay in BEER, love or whatever!

**Comment by grassjelly** [comment]
Closing this @burf2000 mate! Thanks!

**Comment by grassjelly** [comment]
Posting the opened thread here: https://groups.google.com/forum/#!searchin/linorobot/hector%7Csort:date/linorobot/v3s6olorGIo/crnkGd7uCgAJ
